### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Fuzuto** [TeamBixby/Gun#3]
**Error: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)
File: plugins/Gun-master/src/TeamBixby/Gun/GunPlugin
Line:  34**

**Comment by Furryjaki1992** [comment]
**Error: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)
File: plugins/Gun-master/src/TeamBixby/Gun/GunPlugin
Line: 34**

**Comment by Adam1609** [comment]
Please update binary to 7.4, dupe of #1
